services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: setiawan
      POSTGRES_DB: data_sewain
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d data_sewain"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  backend:
    image: alif10231056/sewain-backend:v2  # ← pull dari Docker Hub
    env_file:
      - ./backend/.env.docker
    environment:
      DB_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: setiawan
      POSTGRES_DB: data_sewain
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command:
      ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    image: alif10231056/sewain-frontend:v2  # ← pull dari Docker Hub
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata: