"""
migrate_reviews.py — Tambah tabel `reviews` untuk fitur review/testimoni.

Jalankan sekali dari folder backend:
    python migrate_reviews.py

Skrip mendeteksi otomatis SQLite vs PostgreSQL dan idempoten:
- Tabel yang sudah ada di-skip
- Index yang sudah ada di-skip
"""

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine, text, inspect

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")
if not DATABASE_URL:
    raise SystemExit("DATABASE_URL tidak ditemukan di .env!")

is_sqlite = DATABASE_URL.startswith("sqlite")
TIMESTAMP_TYPE = "TIMESTAMP" if is_sqlite else "TIMESTAMP WITH TIME ZONE"

CREATE_TABLE_SQL = f"""
CREATE TABLE IF NOT EXISTS reviews (
    id          INTEGER PRIMARY KEY {"AUTOINCREMENT" if is_sqlite else "GENERATED BY DEFAULT AS IDENTITY"},
    rental_id   INTEGER NOT NULL,
    user_id     INTEGER NOT NULL,
    item_id     INTEGER NOT NULL,
    admin_id    INTEGER NOT NULL,
    rating      INTEGER NOT NULL,
    komentar    TEXT,
    created_at  {TIMESTAMP_TYPE} NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  {TIMESTAMP_TYPE} DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_review_rental       UNIQUE (rental_id),
    CONSTRAINT ck_review_rating_range CHECK (rating >= 1 AND rating <= 5),
    CONSTRAINT fk_review_rental FOREIGN KEY (rental_id) REFERENCES rentals (id) ON DELETE CASCADE,
    CONSTRAINT fk_review_user   FOREIGN KEY (user_id)   REFERENCES users   (id) ON DELETE CASCADE,
    CONSTRAINT fk_review_item   FOREIGN KEY (item_id)   REFERENCES items   (id) ON DELETE CASCADE,
    CONSTRAINT fk_review_admin  FOREIGN KEY (admin_id)  REFERENCES admins  (id) ON DELETE CASCADE
);
"""

INDEXES = [
    "CREATE INDEX IF NOT EXISTS ix_review_item  ON reviews (item_id)",
    "CREATE INDEX IF NOT EXISTS ix_review_admin ON reviews (admin_id)",
    "CREATE INDEX IF NOT EXISTS ix_review_user  ON reviews (user_id)",
]


def run_migration():
    engine = create_engine(DATABASE_URL)
    print(f"[*] Target DB: {'SQLite' if is_sqlite else 'PostgreSQL'}")
    print(f"[*] URL: {DATABASE_URL.split('@')[-1] if '@' in DATABASE_URL else DATABASE_URL}\n")

    inspector = inspect(engine)
    existing_tables = set(inspector.get_table_names())

    with engine.begin() as conn:
        if "reviews" in existing_tables:
            print("  [SKIP] tabel `reviews` sudah ada")
        else:
            try:
                conn.execute(text(CREATE_TABLE_SQL))
                print("  [OK]   tabel `reviews` dibuat")
            except Exception as e:
                print(f"  [ERR]  membuat tabel reviews → {e}")
                return

        for idx_sql in INDEXES:
            try:
                conn.execute(text(idx_sql))
                print(f"  [OK]   {idx_sql}")
            except Exception as e:
                print(f"  [WARN] {idx_sql} → {e}")

    print("\nSelesai.")


if __name__ == "__main__":
    run_migration()
